### ISSUE TITLE
Dataset ideas

### ISSUE THREAD

**Issue by katerinkus** [UBC-MDS/group_25_python#1]
We can put links to your datasets along with visualization ideas here.

**Comment by katerinkus** [comment]
Tree dataset: [link](https://opendata.vancouver.ca/explore/dataset/street-trees/table/?disjunctive.species_name&disjunctive.common_name&disjunctive.height_range_id)

**Cherry blossom dashboard**
- Visualize top cherry blossom species types by the neighbourhood
- Visualize cherry blossom count by neighbourhood
- Visualize a map with cherry blossom density (i.e. darker colour more blossoms)
- Display blooming dates for top cherry blossom trees (that would need to come from Wikipedia, we can manually add that)
- Display tree trunk width by cherry blossom species
- Show a map with tree locations (may be too difficult to do)

**Comment by ytz** [comment]
[2021 Kaggle Machine Learning & Data Science Survey](https://www.kaggle.com/c/kaggle-survey-2021/overview)

Potential target users: 

- HR/Recruitment interested in trends for data scientist (eg. pay benchmark)
- Tech company doing market research, interested in trend of ML tooling, framework etc.

**Comment by gfairbro** [comment]
Gapminder: https://www.gapminder.org/data/

I have grabbed all the population, energy usage per person, and a sustainability index datasets and done a preliminary melt and combination of them. I thought we could plot sustainability index by energy consumption per person, interactive by energy type, country and maybe by region (needs some more wrangling for that) for the last 75 years.

**Comment by showcy** [comment]
[Global Terrorism Database - START.umd.edu |](https://www.start.umd.edu/gtd/)

Potential target users:
- Any researchers who are interested in global security problem.
- Potential immigrants want to find a safer place to immigrate.

**Comment by katerinkus** [comment]
Here are my thoughts in the order of preference:

1. Kaggle Data Science statistics **or** Cherry blossom dataset
2. Gapminder (energy, etc.)
3. Terrorism attacks (nothing personal, just the last month has been crazy in terms of politics in the world so it would be nice to do something more positive or neutral)

**Comment by ytz** [comment]
1. Cherry Blossom
2. Kaggle
3. Gapminder
4. Global Terrorism

**Comment by gfairbro** [comment]
1. Cherry
2. Gapminder
3. Data Scientist
4. Terrorism

**Comment by showcy** [comment]
1. Data Scientist
2. Cherry
3. Gapminder

**Comment by gfairbro** [comment]
Cherry Blossoms it is!
