### ISSUE TITLE
Proposal - Section 1: Motivation and Purpose

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/group_25_python#5]
In a few sentences, provide motivation for why you are creating a dashboard. Who is your target audience, and what role are you embodying? What problem could your dashboard solve for the intended user? You can read the [Project background](https://pages.github.ubc.ca/mds-2021-22/DSCI_532_viz-2_students/materials/release/milestone1/milestone1.html#project-background) section for some rough ideas. Be brief and clear.

**Comment by gfairbro** [comment]
Motivation and purpose has been drafted here:
https://docs.google.com/document/d/143TMM4pOCQsLjFLRYCfNSGIIJ3o8BTKmWYxzFS2v7Y4/edit#heading=h.cfbqvexr2d9t

Please feel free to suggest or make further edits to align with other sections, or let me know if you have other feedback.
